# dont i hate this shit

im manually translating the slides

### why numpy and not pure python

[../0/tutorial2.ipynb#numpy](../0/tutorial2.ipynb#numpy)

### honestly

[numpy beginners click here](https://numpy.org/doc/stable/user/absolute_beginners.html)

## import steps. use for import

you may need to:


In [ ]:
pip install numpy matplotlib

In [1]:
import numpy as np

## usage

make the list in python and then you np.array it and then feed the numpy array to numpy functions

notice: make it

1. with same size: `all(len(i) == len(j) for i in pyarray for j in pyarray) == True`
2. all elements have same type `all(type(i) == type(r[0]) for i in r for r in pyarray) == True`

then you will be able to harness the peak of numpy. Or else goodbye


In [2]:
pyarray = [
    [1, 2, 3],
    [4, 5, 6],
]


numpy_array = np.array(pyarray)

pyarray, numpy_array

([[1, 2, 3], [4, 5, 6]],
 array([[1, 2, 3],
        [4, 5, 6]]))

the 3:11:2 notation in python is called a slice object. numpy (probably) modified its `array.__index__` to yk accommodate to dimensions

so normally you wouldnt fit more than one thing in that bracket: now you can! pretty great


In [3]:
newarr = numpy_array[:, 1:3]
newarr

array([[2, 3],
       [5, 6]])

kinda cool. normally it would be:


In [4]:
[i[1:3] for i in pyarray[:]]  # uh why so complicated

[[2, 3], [5, 6]]

remember this: Python lists count from zero. Everything related to computer memory counts from 0. only Maniacs count from 1.

also a tip for me actually, for i struggle with matrix rows and columns: `m2d[0,:]` is first Row. `m2d[:, 0]` is first Column.  
row goes across. row number x is counted top down. Column goes top down. column number x is counted left to right


### numpy array (matrix) operations

the slides (and numpy also) have all the shit: the slice which we just covered, np.transpose `'`, np.matmul `*`, np.multiply `.*`, matrix divide `/` maybe with np.dot and np.linarg.inv, np.divide `./`, concat arrays with np.concatenate np.stack or np.block etc.

### math functions

infinitely easier than matlab with python def

you know exactly what this means:

```python
def function(x):
    return 3*x + 2
```

this WILL work with ndarrays as they do have `__mul__` `__rmul__` and `__add__`

as opposed to matlab with its cumbersome ahh syms


# ahh

## ones a 3\*3


In [5]:
ones3x3 = np.ones((3, 3))
ex6_A = ones3x3
ex6_A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## transpose can be accessible by default with .T, but i use transpose for a new one.

why does this exist. transpose of ones is a ones. why do you do this.


In [6]:
ex6_B = np.transpose(ex6_A)
ex6_B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## sum is just + lmao


In [7]:
ex6_sum = ex6_A + ex6_B
ex6_sum

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

## mat mul


In [8]:
ex6_AxB = ex6_A @ ex6_B
ex6_BxA = ex6_B @ ex6_A
ex6_AxB, ex6_BxA

(array([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]),
 array([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]))

## A += 2


In [9]:
ex6_Aplus = ex6_A + 2
ex6_Aplus

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

shit example be fr
