# Python tutorial

this is a python tutorial in jupyter notebook! this will serve as a continuation of that last one.

## but last one is ugh

ok mr complainer here we go:

### basic

In [1]:
x = 3  # variable = value
x = 31.28  # float value

x = 3 + 5
assert x == 8

above is an interactive piece of code. you will press run and it will remember.

If you didnt press run this one will show error:

In [2]:
try:
    x
except NameError:  # last code block define x
    print("play the last code block broski")
else:  # last code block ran
    print("thats right")

thats right


### containers

these are some of the containers.

list, dict, set is mutable,  
dict keys and set items are unique,  
index list and tuple by index and dict by keys.

In [4]:
my_list = ["this", "is", "a", "list"]
my_dict = {"my key": "my value", "my life": "my rules", "my style": "my attitute"}

assert my_list[1] == "is"  # not "this"
assert my_list[-1] == "list"

In [5]:
my_longer = list(range(20))  # 0 -> 19

assert my_longer[2:5] == [2, 3, 4]  # slice
assert my_longer[:4] == [0, 1, 2, 3]  # blank start for 0
assert my_longer[3::5] == [3, 8, 13, 18]  # blank stop for past end
assert my_longer[18:6:-4] == [18, 14, 10]  # empty/no step for 1
assert my_longer[:-3:8] == [0, 8, 16]

### function

function is declared with `def`:

In [3]:
def my_function(a: int, b: int) -> int:
    return a + b

you can violate type hints:

In [4]:
my_function("hello ", "world!")  # dont do this
my_function(2, 6)

8

### control flow, conditional

In [ ]:
if 3 + 5 == 6:
    print("3 + 5 = 6")
elif 3 + 5 == 7:
    print("3 + 5 = 7")
elif 3 + 5 == 8:
    print("3 + 5 == 8")
else:
    print("D: None of the above")

In [5]:
container = [1, 11, 5, 17]
sum_ = 0
for element in container:
    sum_ += element
sum_

34

In [1]:
x = 0
while True:
    x += 1

    if x > 20:
        break

In [ ]:
match 2 + 3:
    case x if x <= 4:
        print("no way")
    case 5:
        print("2 + 3 = 5")
    case x if x > 6:  # match doesnt need to cover all cases
        print("woah")

`break` and `continue` work with the innermost for/while loop. also works with match i think i never tested

### Exceptions

exceptions are python errors. you can let it crash, catch with try except, or raise one yourself.

Some common ones are `ValueError` `TypeError` and `OSError` type shit

In [ ]:
try:
    raise ValueError("value eroe")
except ValueError as error:
    print("raised", error)

### class

class. methods. backbone of python.

In [6]:
class Foo:
    bar = "baz"

    def quux(tis, arg1):
        return arg1, 42


# usage:

fbar = Foo()

fbar.quux("spam")

('spam', 42)

looking ass.

class has class properties and instance properties. instance probably goes self.something, while class Foo.something.

it can be a number, a string, a list (not advised), or a function?

for a function in a class it would be marked a classmethod (`@classmethod`) and with classmethods the instance get passed in first arg.
`@staticmethod` used in the class block revert this behavior.

check the tutorial.py file im lazy

In [7]:
# everything is a class so your list is also a class
# so it has classmethods:

list_lda = [1, 4, 7]
list_lda.append(10)
list_lda.reverse()
list_lda.pop(), list_lda

(1, [10, 7, 4])

do research broski

## more python stuff

### map and filter

alot of time you would want to do stuff with the List and you would want to have a look at the builtin `map()` or `filter()` or those kind of functions:

what they do is:

```python
collection = [something, something_else,]
def function(x) -> y: ...

new_collection = map(function, collection) 
# => each x you run function on it and it returns y.
# put that y in the place x would be in the new_collection

condition = lambda x: x == True
# lambda is a kind of mini throwaway function. you know closures? yes that
# but it can only do one thing. one singular expression fits in there. life is bad.
# tips. use def if this function deserves a name. for example ReLU is just
# ReLU = lambda x: x if x > 0 else 0
# but you would use want to do def ReLU(x: float) -> float as much as possible

filtered_collection = filter(condition, collection)
# check for condition for each element of condition and append it into filtered_collection
```

remember map and filter doesnt return a list back but a special generator object so you would have to call list() on it to use as list.

why? for performance. generator is lazy.

we also have this thing:

### Python list comprehension

comprehension. fuck do i know what it means. you dont know half these words and so do i.

a simple way to do fiter_map ig

In [ ]:
# you would do this:
oldlist = list(range(1, 40, 3))
newlist = []
for i in oldlist:  # notice this
    if i % 5 == 0:  # notice this
        newlist.append(i)

list_shorthand = [i for i in oldlist if i % 5 == 0]

assert list_shorthand == newlist  # same thing!

its: 
```python
something(vals) for vals in collection if condition(vals) if condition2(vals) if etc.
```
and `something(vals)` could well be another comprehension.

notice for in if. strictly for in if, and not if for in. that if is of something else.

oh but `something if condition else something_else` i also see how is that

well that is another shorthand unrelated, but if you can use sure go ahead

its kinda like the Ternary conditional operator `cond ? true_expr : false_expr` in c or typescript and yes you can go crazy with it just like with typescript

## what the fuck is this half code half document

jupyter. very flexible very dynamic. you can have jupyter running on browser or on vscode i think

jupyter has a lot of thingimajig suitable for data engineers.


In [8]:
try:
    import numpy as np
except ImportError:
    print("python -m pip install numpy")
else:
    print(np.array([[1, 5, 7], [2, 6, 8], [3, 4, 9]]))

[[1 5 7]
 [2 6 8]
 [3 4 9]]


for example the shit we are very much working with in the course: numpy. matplotlib. scipy maybe

### numpy

so you just learned python. SCRAP ALL THAT SHIT we learn a new language called Numpy.

fuck you mean numpy a new language?

see. numpy dont use python for the bulk of its operations. python is slow, they say, but c is fast. numpy is made in C.

so numpy dont use python types. numpy uses its own types. its own functions. almost all of them not from python but from C for all the speed

try ctrl space the just imported np object. snoop around. its complicated. theres so much. we dont use much of it tho.